spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: scott
    password: scott
    url: jdbc:oracle:thin:@localhost:1521:orcl
  application:
    name: myblog
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
server:
  servlet:
    application-display-name: myblog
    context-path: /myblog
